### ISSUE TITLE
Let us specify the path to brew - Ensure that brew is in the environment

### ISSUE THREAD

**Issue by vesper8** [AndrewMD5/orion#3]
I'm a developer and use brew a lot. My `brew` is the arm version and I have another brew which is aliased to `ibrew`

I get an error when trying to use your tool because it assumes that the main `brew` installed will be the `arch -x86_64` version used for the gameportingtoolkit.

Please don't make this assumption, it will be wrong for everyone who uses homebrew for development. Let us specify these paths instead.

Many thanks!

**Comment by andrewmd5** [comment]
the path it defaults to is the x86_64 brew that can be installed alongside the ARM version (which gameportingtoolkit requires) - that being said you can now specify your own brew path https://github.com/AndrewMD5/orion/releases/tag/0.0.3
