### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by montanaflynn** [AndrewMD5/orion#4]
When I run orion and launch Steam it opens an app wine64-preloader that is just window of a black screen. After a few seconds it opens a second app with the same name in the dock but in the menu bar has a name of `steamwebhelper` that has no window.

Any ideas? I'm running sonoma and have installed everything in this guide: https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit

I had the same problem launching steam as suggested in the same guide where it mentioned this is a common issue and retrying should help.

```
gameportingtoolkit ~/steam-port 'C:\Program Files (x86)/Steam/steam.exe'
```

and 

```
MTL_HUD_ENABLED=1 WINEESYNC=1 WINEPREFIX=~/steam-port /usr/local/Cellar/game-porting-toolkit/1.0/bin/wine64 'C:\Program Files (x86)\Steam\steam.exe'
```

**Comment by andrewmd5** [comment]
not much this tool can do to fix it, but my suggestion would be to install freetype and ensure it’s linked. that solves it for me.

**Comment by montanaflynn** [comment]
freetype is installed, not sure what you mean by linked, I just installed it with `brew install freetype` with the x86_64 brew.

I did finally get it working with the second command recommended in the guide I linked.
